# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 21:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line1', models.CharField(max_length=200)),
                ('line2', models.CharField(blank=True, max_length=200, null=True)),
                ('postcode', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=150)),
                ('note', models.TextField(blank=True, null=True)),
                ('address_type', models.CharField(choices=[('WORK', 'Work'), ('HOME', 'Home')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('medium', models.CharField(choices=[('LINKEDIN', 'LINKEDIN'), ('TWITTER', 'Twitter'), ('GITHUB', 'GitHub'), ('MEDIUM', 'Medium'), ('FACEBOOK', 'Facebook'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('FACE2FACE', 'Face to face'), ('POST', 'Post')], max_length=200)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=140)),
                ('middle_name', models.CharField(blank=True, max_length=140, null=True)),
                ('last_name', models.CharField(max_length=140)),
                ('job_title', models.CharField(blank=True, max_length=140, null=True)),
                ('industry', models.CharField(blank=True, max_length=140, null=True)),
                ('salutation', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, max_length=300, null=True)),
                ('medium', models.CharField(choices=[('LINKEDIN', 'LINKEDIN'), ('TWITTER', 'Twitter'), ('GITHUB', 'GitHub'), ('MEDIUM', 'Medium'), ('FACEBOOK', 'Facebook'), ('EMAIL', 'Email'), ('PHONE', 'Phone'), ('FACE2FACE', 'Face to face'), ('POST', 'Post')], max_length=50)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Birthday'), ('WORK_ANNIVERSARY', 'Work Anniversary'), ('WEDDING_ANNIVERSARY', 'Wedding Anniversary'), ('BIRTHDAY_OF_RELATION', 'Birthday of a loved one')], max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=datetime.datetime.utcnow)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='communication',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact'),
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact'),
        ),
    ]
